const themeMoveThemes = [
  {
    url: 'https://themeforest.net/item/minimog-the-high-converting-ecommerce-wordpress-theme',
    themeId: 36947163,
    name: 'MinimogWP',
    fixedSales: 2519,
    fixedReviews: 102,
    color: '#ED2B33FF',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/ecomm-the-powerful-woocommerce-theme',
    themeId: 34750491,
    name: 'Ecomm',
    fixedSales: 195,
    fixedReviews: 10,
    color: '#4b92e5',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/makeaholic-beauty-cosmetics-wordpress-theme',
    themeId: 32981860,
    name: 'Makeaholic',
    fixedSales: 375,
    fixedReviews: 14,
    color: '#7f4afa',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/unicamp-university-and-college-wordpress-theme',
    themeId: 32057449,
    name: 'Unicamp',
    fixedSales: 456,
    fixedReviews: 9,
    color: '#b176e2',
    category: ['Education'],
  },
  {
    url: 'https://themeforest.net/item/edumall-lms-education-wordpress-theme',
    themeId: 29240444,
    name: 'EduMall',
    fixedSales: 2143,
    fixedReviews: 106,
    color: '#b1489e',
    category: ['Education'],
  },
  {
    url: 'https://themeforest.net/item/medizin-medical-woocommerce-theme',
    themeId: 26538545,
    name: 'Medizin',
    fixedSales: 948,
    fixedReviews: 28,
    color: '#b66e3f',
    category: ['Retail'],
  },
  {
    url: 'https://themeforest.net/item/maxcoach-online-courses-education-wp-theme',
    themeId: 26051639,
    name: 'MaxCoach',
    fixedSales: 2838,
    fixedReviews: 95,
    category: ['Education'],
  },
  {
    url: 'https://themeforest.net/item/billey-creative-multipurpose-wordpress-theme',
    themeId: 25656507,
    name: 'Billey',
    fixedSales: 1283,
    fixedReviews: 40,
    color: '#4c9aaf',
    category: ['Creative', 'Portfolio'],
  },
  {
    url: 'https://themeforest.net/item/smilepure-dental-medical-care-wordpress-theme',
    themeId: 25178753,
    name: 'SmilePure',
    fixedSales: 229,
    fixedReviews: 11,
    color: '#4282cd',
    category: ['Retail', 'Health & Beauty'],
  },
  {
    url: 'https://themeforest.net/item/retrolie-vintage-retro-multipurpose-wordpress-theme',
    themeId: 23673799,
    name: 'Vintage Retrolie',
    fixedSales: 286,
    fixedReviews: 11,
    color: '#997afc',
    category: ['Creative'],
  },
  {
    url: 'https://themeforest.net/item/it-solutions-mitech-technology-it-services-solutions-wordpress-theme',
    themeId: 23629596,
    name: 'Mitech',
    fixedSales: 2179,
    fixedReviews: 69,
    color: '#9f41dc',
    category: ['Technology'],
  },
  {
    url: 'https://themeforest.net/item/learts-woocommerce-handmade-shop-wordpress-theme',
    themeId: 23379196,
    name: 'LeArts',
    fixedSales: 1260,
    fixedReviews: 47,
    color: '#da62c4',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/aeroland-responsive-app-landing-and-website-wordpress-theme',
    themeId: 23314522,
    name: 'AeroLand',
    fixedSales: 506,
    fixedReviews: 18,
    color: '#7a4621',
    category: ['Technology', ' Software'],
  },
  {
    url: 'https://themeforest.net/item/openlane-a-gutenberg-wordpress-theme-for-business',
    themeId: 22626300,
    name: 'Openlane',
    fixedSales: 134,
    fixedReviews: 10,
    color: '#97933e',
    category: ['Corporate'],
  },
  {
    url: 'https://themeforest.net/item/healsoul-medical-and-healthcare-service-wordpress-theme',
    themeId: 23022324,
    name: 'Healsoul',
    fixedSales: 1088,
    fixedReviews: 45,
    color: '#33798c',
    category: ['Retail', 'Health & Beauty'],
  },
  {
    url: 'https://themeforest.net/item/brook-creative-multipurpose-wordpress-theme',
    themeId: 22675741,
    name: 'Brook',
    fixedSales: 2193,
    fixedReviews: 74,
    color: '#4b92e5',
    category: ['Creative', 'Portfolio'],
  },
  {
    url: 'https://themeforest.net/item/tractor-industrial-manufacturing-wordpress-theme',
    themeId: 22437428,
    name: 'Tractor',
    fixedSales: 630,
    fixedReviews: 32,
    color: '#7f4afa',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/businext-supreme-businesses-and-financial-institutions-wordpress-theme',
    themeId: 21535442,
    name: 'Businext',
    fixedSales: 776,
    fixedReviews: 38,
    color: '#b176e2',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/lezada-minimal-creative-woocommerce-wordpress-theme',
    themeId: 21949766,
    name: 'Lezada',
    fixedSales: 703,
    fixedReviews: 39,
    color: '#b1489e',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/atomlab-multipurpose-startup-wordpress-theme',
    themeId: 20939963,
    name: 'Atomlab',
    fixedSales: 1152,
    fixedReviews: 52,
    color: '#b66e3f',
    category: ['Technology', 'Software'],
  },
  {
    url: 'https://themeforest.net/item/amely-ecommerce-wordpress-theme-for-woocommerce',
    themeId: 20858805,
    name: 'Amely',
    fixedSales: 1721,
    fixedReviews: 86,
    color: '#bdb24e',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/conebrick-a-masterly-wordpress-theme-for-construction',
    themeId: 20991064,
    name: 'Conebrick',
    fixedSales: 200,
    fixedReviews: 9,
    color: '#4c9aaf',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/moody-a-modern-flexible-multipurpose-wordpress-theme',
    themeId: 20524765,
    name: 'Moody',
    fixedSales: 733,
    fixedReviews: 33,
    color: '#4282cd',
    category: ['Creative', 'Portfolio'],
  },
  {
    url: 'https://themeforest.net/item/wilson-multipurpose-wordpress-theme',
    themeId: 20300743,
    name: 'Wilson',
    fixedSales: 342,
    fixedReviews: 28,
    color: '#4282cd',
    category: ['Creative', 'Portfolio'],
  },
  {
    url: 'https://themeforest.net/item/robin-a-furniture-woocommerce-wordpress-theme',
    themeId: 20045842,
    name: 'Robin',
    fixedSales: 544,
    fixedReviews: 32,
    color: '#9f41dc',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/arden-a-sharp-modern-multipurpose-wordpress-theme',
    themeId: 19710416,
    name: 'Arden',
    fixedSales: 778,
    fixedReviews: 50,
    color: '#da62c4',
    category: ['Creative', 'Portfolio'],
  },
  {
    url: 'https://themeforest.net/item/trio-a-super-mature-multipurpose-wordpress-theme',
    themeId: 19491254,
    name: 'Trio',
    fixedSales: 123,
    fixedReviews: 14,
    color: '#7a4621',
    category: ['Creative'],
  },
  {
    url: 'https://themeforest.net/item/nine-studio-a-film-maker-studio-agency-blogger-wordpress-theme',
    themeId: 19303651,
    name: '9Studio',
    fixedSales: 708,
    fixedReviews: 35,
    color: '#97933e',
    category: ['Entertainment', 'Film & TV'],
  },
  {
    url: 'https://themeforest.net/item/organie-an-organic-store-farm-cake-flower-shop-woocommerce-theme',
    themeId: 18777939,
    name: 'Organie',
    fixedSales: 985,
    fixedReviews: 53,
    color: '#33798c',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/organik-an-appealing-organic-store-farm-bakery-woocomerce-theme',
    themeId: 17678863,
    name: 'Organik',
    fixedSales: 1898,
    fixedReviews: 114,
    color: '#4b92e5',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/buildplus-construction-wordpress-theme',
    themeId: 17590237,
    name: 'BuildPlus',
    fixedSales: 245,
    fixedReviews: 22,
    color: '#7f4afa',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/molly-multipurpose-woocommerce-wordpress-theme',
    themeId: 15300928,
    name: 'Molly',
    fixedSales: 320,
    fixedReviews: 30,
    color: '#b176e2',
    category: ['eCommerce', 'WooCommerce'],
  },
  {
    url: 'https://themeforest.net/item/dione-enterprise-multipurpose-wordpress-theme',
    themeId: 15945779,
    name: 'Dione',
    fixedSales: 480,
    fixedReviews: 26,
    color: '#b1489e',
    category: ['Creative', 'Portfolio'],
  },
  {
    url: 'https://themeforest.net/item/heli-creative-multipurpose-wordpress-theme',
    themeId: 14438769,
    name: 'Heli',
    fixedSales: 2267,
    fixedReviews: 162,
    color: '#b66e3f',
    category: ['Creative', 'Portfolio'],
  },
  {
    url: 'https://themeforest.net/item/financeplus-finance-business-wordpress-theme',
    themeId: 14800887,
    name: 'FinancePlus',
    fixedSales: 1169,
    fixedReviews: 88,
    color: '#bdb24e',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/lawyer-attorneys-a-law-office-wordpress-theme',
    themeId: 13928210,
    name: 'Lawyer Attorneys',
    fixedSales: 579,
    fixedReviews: 29,
    color: '#4c9aaf',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/polygon-a-powerful-multipurpose-wp-theme',
    themeId: 13244811,
    name: 'Polygon',
    fixedSales: 1365,
    fixedReviews: 66,
    color: '#4282cd',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/hair-salon-a-barber-wordpress-theme',
    themeId: 13107025,
    name: 'Hair Salon',
    fixedSales: 427,
    fixedReviews: 21,
    color: '#997afc',
    category: ['Retail', 'Health & Beauty'],
  },
  {
    url: 'https://themeforest.net/item/renovation-home-maintenance-repair-service-theme',
    themeId: 11444549,
    name: 'Renovation',
    fixedSales: 2098,
    fixedReviews: 108,
    color: '#9f41dc',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/zebre-minimal-agency-porfolio-wp-theme',
    themeId: 12528341,
    name: 'Zebre',
    fixedSales: 416,
    fixedReviews: 23,
    color: '#da62c4',
    category: ['Creative', 'Portfolio'],
  },
  {
    url: 'https://themeforest.net/item/woodworker-carpentry-wordpress-theme',
    themeId: 12446501,
    name: 'WoodWorker',
    fixedSales: 829,
    fixedReviews: 43,
    color: '#7a4621',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/lily-an-elegant-wordpress-blog-theme',
    themeId: 12232187,
    name: 'Lily',
    fixedSales: 725,
    fixedReviews: 56,
    color: '#97933e',
    category: ['Blog', 'Magazine', 'Personal'],
  },
  {
    url: 'https://themeforest.net/item/transport-transport-logistic-warehouse-wp-',
    themeId: 12054479,
    name: 'Transport',
    fixedSales: 1596,
    fixedReviews: 101,
    color: '#33798c',
    category: ['Corporate', 'Business'],
  },
  {
    url: 'https://themeforest.net/item/structure-construction-wordpress-theme',
    themeId: 10798442,
    name: 'Structure',
    fixedSales: 3982,
    fixedReviews: 261,
    color: '#4b92e5',
    category: ['Corporate', 'Business'],
  },
];

export const otherThemes = [
  {
    url: 'https://themeforest.net/item/construction-wp-construction-building-business',
    themeId: 10439297,
    name: 'Construction Wordpress Theme',
    fixedSales: 10005,
    fixedReviews: 322,
  },
  {
    url: 'https://themeforest.net/item/constructo-wp-construction-business-theme',
    themeId: 9835983,
    name: 'Constructo',
    fixedSales: 6607,
    fixedReviews: 232,
  },
  {
    url: 'https://themeforest.net/item/renovate-construction-renovation-wordpress-theme',
    themeId: 11789093,
    name: 'Renovate',
    fixedSales: 5347,
    fixedReviews: 230,
  },
  {
    url: 'https://themeforest.net/item/construction-construction-building-company',
    themeId: 11032581,
    name: 'Construction',
    fixedSales: 4424,
    fixedReviews: 146,
  },
  {
    url: 'https://themeforest.net/item/wilmr-construction-wordpress-theme',
    themeId: 23695848,
    name: 'Wilmër',
    fixedSales: 3131,
    fixedReviews: 51,
  },
  {
    url: 'https://themeforest.net/item/efor-coaching-online-courses-wordpress-theme',
    themeId: 22838389,
    name: 'Efor',
    fixedSales: 4084,
    fixedReviews: 71,
  },
  {
    url: 'https://themeforest.net/item/dotlife-coach-speaker-wordpress',
    themeId: 23858076,
    name: 'DotLife',
    fixedSales: 3365,
    fixedReviews: 75,
  },
  {
    url: 'https://themeforest.net/item/ed-school-elementary-middle-and-highschool-wordpress-theme',
    themeId: 19618075,
    name: 'Ed School',
    fixedSales: 3320,
    fixedReviews: 75,
  },
  {
    url: 'https://themeforest.net/item/eikra-education-wordpress-theme',
    themeId: 20950897,
    name: 'Eikra',
    fixedSales: 2600,
    fixedReviews: 87,
  },
  {
    url: 'https://themeforest.net/item/skilled-school-education-courses-wordpress-theme',
    themeId: 14564174,
    name: 'Skilled',
    fixedSales: 2446,
    fixedReviews: 68,
  },
  {
    url: 'https://themeforest.net/item/woodmart-woocommerce-wordpress-theme',
    themeId: 20264492,
    name: 'WoodMart',
    fixedSales: 53929,
    fixedReviews: 2162,
  },
  {
    url: 'https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme',
    themeId: 9207399,
    name: 'Porto',
    fixedSales: 79748,
    fixedReviews: 3538,
  },
  {
    url: 'https://themeforest.net/item/pressmart-modern-elementor-woocommerce-wordpress-theme',
    themeId: 39241221,
    name: 'PressMart',
    fixedSales: 996,
    fixedReviews: 41,
  },
  {
    url: 'https://themeforest.net/item/ciyashop-responsive-multipurpose-woocommerce-wordpress-theme',
    themeId: 22055376,
    name: 'CiyaShop',
    fixedSales: 2966,
    fixedReviews: 206,
  },
  {
    url: 'https://themeforest.net/item/kapee-fashion-store-woocommerce-theme',
    themeId: 24187521,
    name: 'Kapee',
    fixedSales: 3368,
    fixedReviews: 172,
  },
  {
    url: 'https://themeforest.net/item/pond-creative-portfolio-agency-wordpress-theme',
    themeId: 10395093,
    name: 'Pond',
    fixedSales: 2175,
    fixedReviews: 91,
  },
  {
    url: 'https://themeforest.net/item/avoc-unique-and-minimal-portfolio-agency-wordpress-theme',
    themeId: 12441050,
    name: 'Avoc',
    fixedSales: 2170,
    fixedReviews: 67,
  },
  {
    url: 'https://themeforest.net/item/air-lightweight-portfolio-photography-wp-theme',
    themeId: 17533013,
    name: 'Air',
    fixedSales: 2126,
    fixedReviews: 55,
  },
  {
    url: 'https://themeforest.net/item/grand-portfolio-responsive-portfolio',
    themeId: 14496218,
    name: 'Grand Portfolio',
    fixedSales: 2323,
    fixedReviews: 104,
  },
  {
    url: 'https://themeforest.net/item/proton-minimal-portfolio-theme',
    themeId: 16565981,
    name: 'Proton',
    fixedSales: 1980,
    fixedReviews: 158,
  },
  {
    url: 'https://themeforest.net/item/ohio-creative-wordpress-theme',
    themeId: 25193838,
    name: 'Ohio',
    fixedSales: 13761,
    fixedReviews: 392,
  },
  {
    url: 'https://themeforest.net/item/lekker-portfolio-wordpress-theme',
    themeId: 27110616,
    name: 'Lekker',
    fixedSales: 2365,
    fixedReviews: 37,
  },
  {
    url: 'https://themeforest.net/item/shiftcv-blog-resume-portfolio-wordpress',
    themeId: 5150965,
    name: 'ShiftCV',
    fixedSales: 2192,
    fixedReviews: 204,
  },
  {
    url: 'https://themeforest.net/item/folie-the-wordpress-website-builder',
    themeId: 19946424,
    name: 'Folie',
    fixedSales: 2188,
    fixedReviews: 48,
  },
  {
    url: 'https://themeforest.net/item/lobo-portfolio-for-freelancers-agencies',
    themeId: 7762848,
    name: 'Lobo',
    fixedSales: 5120,
    fixedReviews: 319,
  },
];

export const compareThemes = {
  Structure: [
    {
      url: 'https://themeforest.net/item/structure-construction-wordpress-theme',
      themeId: 10798442,
      name: 'Structure',
      priority: true,
      fixedSales: 3982,
      fixedReviews: 261,
      color: '#4b92e5',
    },
    {
      url: 'https://themeforest.net/item/construction-wp-construction-building-business',
      themeId: 10439297,
      name: 'Construction Wordpress Theme',
      fixedSales: 10005,
      fixedReviews: 322,
    },
    {
      url: 'https://themeforest.net/item/constructo-wp-construction-business-theme',
      themeId: 9835983,
      name: 'Constructo',
      fixedSales: 6607,
      fixedReviews: 232,
    },
    {
      url: 'https://themeforest.net/item/renovate-construction-renovation-wordpress-theme',
      themeId: 11789093,
      name: 'Renovate',
      fixedSales: 5347,
      fixedReviews: 230,
    },
    {
      url: 'https://themeforest.net/item/construction-construction-building-company',
      themeId: 11032581,
      name: 'Construction',
      fixedSales: 4424,
      fixedReviews: 146,
    },
    {
      url: 'https://themeforest.net/item/wilmr-construction-wordpress-theme',
      themeId: 23695848,
      name: 'Wilmër',
      fixedSales: 3131,
      fixedReviews: 51,
    },
  ],
  MaxCoach: [
    {
      url: 'https://themeforest.net/item/maxcoach-online-courses-education-wp-theme',
      themeId: 26051639,
      name: 'MaxCoach',
      priority: true,
      fixedSales: 2838,
      fixedReviews: 95,
    },
    {
      url: 'https://themeforest.net/item/efor-coaching-online-courses-wordpress-theme',
      themeId: 22838389,
      name: 'Efor',
      fixedSales: 4084,
      fixedReviews: 71,
    },
    {
      url: 'https://themeforest.net/item/dotlife-coach-speaker-wordpress',
      themeId: 23858076,
      name: 'DotLife',
      fixedSales: 3365,
      fixedReviews: 75,
    },
    {
      url: 'https://themeforest.net/item/ed-school-elementary-middle-and-highschool-wordpress-theme',
      themeId: 19618075,
      name: 'Ed School',
      fixedSales: 3320,
      fixedReviews: 75,
    },
    {
      url: 'https://themeforest.net/item/eikra-education-wordpress-theme',
      themeId: 20950897,
      name: 'Eikra',
      fixedSales: 2600,
      fixedReviews: 87,
    },
    {
      url: 'https://themeforest.net/item/skilled-school-education-courses-wordpress-theme',
      themeId: 14564174,
      name: 'Skilled',
      fixedSales: 2446,
      fixedReviews: 68,
    },
  ],
  MinimogWP: [
    {
      url: 'https://themeforest.net/item/minimog-the-high-converting-ecommerce-wordpress-theme',
      themeId: 36947163,
      name: 'MinimogWP',
      fixedSales: 2519,
      priority: true,
      fixedReviews: 102,
      color: '#ED2B33FF',
    },
    {
      url: 'https://themeforest.net/item/woodmart-woocommerce-wordpress-theme',
      themeId: 20264492,
      name: 'WoodMart',
      fixedSales: 53929,
      fixedReviews: 2162,
    },
    {
      url: 'https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme',
      themeId: 9207399,
      name: 'Porto',
      fixedSales: 79748,
      fixedReviews: 3538,
    },
    {
      url: 'https://themeforest.net/item/pressmart-modern-elementor-woocommerce-wordpress-theme',
      themeId: 39241221,
      name: 'PressMart',
      fixedSales: 996,
      fixedReviews: 41,
    },
    {
      url: 'https://themeforest.net/item/ciyashop-responsive-multipurpose-woocommerce-wordpress-theme',
      themeId: 22055376,
      name: 'CiyaShop',
      fixedSales: 2966,
      fixedReviews: 206,
    },
    {
      url: 'https://themeforest.net/item/kapee-fashion-store-woocommerce-theme',
      themeId: 24187521,
      name: 'Kapee',
      fixedSales: 3368,
      fixedReviews: 172,
    },
  ],
  Heli: [
    {
      url: 'https://themeforest.net/item/heli-creative-multipurpose-wordpress-theme',
      themeId: 14438769,
      name: 'Heli',
      priority: true,
      fixedSales: 2267,
      fixedReviews: 162,
      color: '#b66e3f',
    },
    {
      url: 'https://themeforest.net/item/pond-creative-portfolio-agency-wordpress-theme',
      themeId: 10395093,
      name: 'Pond',
      fixedSales: 2175,
      fixedReviews: 91,
    },
    {
      url: 'https://themeforest.net/item/avoc-unique-and-minimal-portfolio-agency-wordpress-theme',
      themeId: 12441050,
      name: 'Avoc',
      fixedSales: 2170,
      fixedReviews: 67,
    },
    {
      url: 'https://themeforest.net/item/air-lightweight-portfolio-photography-wp-theme',
      themeId: 17533013,
      name: 'Air',
      fixedSales: 2126,
      fixedReviews: 55,
    },
    {
      url: 'https://themeforest.net/item/grand-portfolio-responsive-portfolio',
      themeId: 14496218,
      name: 'Grand Portfolio',
      fixedSales: 2323,
      fixedReviews: 104,
    },
    {
      url: 'https://themeforest.net/item/proton-minimal-portfolio-theme',
      themeId: 16565981,
      name: 'Proton',
      fixedSales: 1980,
      fixedReviews: 158,
    },
  ],
  Brook: [
    {
      url: 'https://themeforest.net/item/brook-creative-multipurpose-wordpress-theme',
      themeId: 22675741,
      name: 'Brook',
      priority: true,
      fixedSales: 2193,
      fixedReviews: 74,
      color: '#4b92e5',
    },
    {
      url: 'https://themeforest.net/item/ohio-creative-wordpress-theme',
      themeId: 25193838,
      name: 'Ohio',
      fixedSales: 13761,
      fixedReviews: 392,
    },
    {
      url: 'https://themeforest.net/item/lekker-portfolio-wordpress-theme',
      themeId: 27110616,
      name: 'Lekker',
      fixedSales: 2365,
      fixedReviews: 37,
    },
    {
      url: 'https://themeforest.net/item/shiftcv-blog-resume-portfolio-wordpress',
      themeId: 5150965,
      name: 'ShiftCV',
      fixedSales: 2192,
      fixedReviews: 204,
    },
    {
      url: 'https://themeforest.net/item/folie-the-wordpress-website-builder',
      themeId: 19946424,
      name: 'Folie',
      fixedSales: 2188,
      fixedReviews: 48,
    },
    {
      url: 'https://themeforest.net/item/lobo-portfolio-for-freelancers-agencies',
      themeId: 7762848,
      name: 'Lobo',
      fixedSales: 5120,
      fixedReviews: 319,
    },
  ],
};

export default themeMoveThemes;
